source 'https://ruby.taobao.org'

gem 'thin'
gem 'rack-cors', require: 'rack/cors'

gem 'bcrypt-ruby', '~> 3.0.0'
gem "kaminari", "~> 0.14.1"
gem 'simplecov', :require => false, :group => :test

gem 'rb-readline'

gem 'pry'
# user
# gem 'devise'

gem "protected_attributes"
# api token
# gem 'simple_token_authentication'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'
gem 'multi_json', '~> 1.0'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
	gem 'guard-rspec', '~> 4.2.8'
	gem "webrat"
	gem "capybara"
	gem "fakeweb", "~> 1.3"
	gem "timecop"
	gem 'selenium-webdriver', '2.35.1'
	gem "rspec", "~> 3.0.0.beta2"
  gem 'rspec-rails', '~> 3.0.0.beta'
	gem "factory_girl_rails", "~> 4.2.1"
	
	gem 'spork-rails', '4.0.0'
  gem 'guard-spork', '1.5.0'
  gem 'childprocess'
	gem 'launchy'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
